Added 'clean' command to dvmc CLI
-> Updated samples directories

diff --git a/tool/dvmc_cli/dvmc b/tool/dvmc_cli/dvmc
--- a/tool/dvmc_cli/dvmc
+++ b/tool/dvmc_cli/dvmc
@@ -38,6 +38,7 @@ dvmc_usage() {
   printf "  %s   Proceeds to dynamical calculations using 'namelist_G.def' to specifie configuration files and './output/zqp_opt.dat' file to access optimized dynamical parameters.\n" "$(green "excitations")   "
   printf "  %s   Merge binary output files\n" "$(green "process-output")"
   printf "  %s   Q-matrix calcultations\n" "$(green "qmatrix")       "
+  printf "  %s   Clean current directory by removing '.def', '.dat' files generated by dvmc.\n" "$(green "clean")         "
   echo
 
   # :command.long_usage
@@ -309,6 +310,48 @@ dvmc_qmatrix_usage() {
   fi
 }
 
+# :command.usage
+dvmc_clean_usage() {
+  if [[ -n $long_usage ]]; then
+    printf "dvmc clean - Clean current directory by removing '.def', '.dat' files generated by dvmc.\n"
+    echo
+
+  else
+    printf "dvmc clean - Clean current directory by removing '.def', '.dat' files generated by dvmc.\n"
+    echo
+
+  fi
+
+  printf "%s\n" "$(bold "Usage:")"
+  printf "  dvmc clean [OPTIONS]\n"
+  printf "  dvmc clean --help | -h\n"
+  echo
+
+  # :command.long_usage
+  if [[ -n $long_usage ]]; then
+    printf "%s\n" "$(bold "Options:")"
+
+    # :command.usage_flags
+    # :flag.usage
+    printf "  %s\n" "$(magenta "--deep, -d")"
+    printf "    Clean the './output' directory from any outputed results and optimized\n    results.\n"
+    echo
+
+    # :command.usage_fixed_flags
+    printf "  %s\n" "$(magenta "--help, -h")"
+    printf "    Show this help\n"
+    echo
+
+    # :command.usage_examples
+    printf "%s\n" "$(bold "Examples:")"
+    printf "  dvmc clean\n"
+    printf "  dvmc clean --deep\n"
+    printf "  dvmc clean -d\n"
+    echo
+
+  fi
+}
+
 # :command.normalize_input
 normalize_input() {
   local arg flags
@@ -573,6 +616,40 @@ dvmc_qmatrix_command() {
 
 }
 
+# :command.function
+dvmc_clean_command() {
+  # src/clean_command.sh
+  # Clean command script
+
+  clean () {
+    # Constants
+    TRASH=$(find . -name "*.def" -o -name "*.dat" -o -name "*.npy" -o -name "sec" -type f)
+    OUTPUT_TRASH=$(find ./output -type f)
+
+    # Script
+    if [[ -z "${TRASH}" ]]; then
+      yellow_bold "[!] Nothing to clean in current directory."
+    else
+      green_bold "[@] Removing '.def', '.dat' and '.npy' generated files..."
+      rm -vf ${TRASH}
+    fi
+
+    if [[ "${args[--deep]}" ]] || [[ "${args[-d]}" ]]; then
+      if [[ -z "${OUTPUT_TRASH}" ]]; then
+        yellow_bold "[!] Nothing to clean in './output' directory."
+        exit 0
+      else
+        yellow_bold "[!] Cleaning './output' directory..."
+        rm -vf ${OUTPUT_TRASH}
+      fi
+    fi
+    green_bold "[@] Cleaning done."
+  }
+
+  clean
+
+}
+
 # :command.parse_requirements
 parse_requirements() {
   # :command.fixed_flags_filter
@@ -639,6 +716,13 @@ parse_requirements() {
       action="qmatrix"
       shift
       dvmc_qmatrix_parse_requirements "$@"
+      shift $#
+      ;;
+
+    clean)
+      action="clean"
+      shift
+      dvmc_clean_parse_requirements "$@"
       shift $#
       ;;
 
@@ -1004,6 +1088,57 @@ dvmc_qmatrix_parse_requirements() {
 
 }
 
+# :command.parse_requirements
+dvmc_clean_parse_requirements() {
+  # :command.fixed_flags_filter
+  while [[ $# -gt 0 ]]; do
+    case "${1:-}" in
+      --help | -h)
+        long_usage=yes
+        dvmc_clean_usage
+        exit
+        ;;
+
+      *)
+        break
+        ;;
+
+    esac
+  done
+
+  # :command.command_filter
+  action="clean"
+
+  # :command.parse_requirements_while
+  while [[ $# -gt 0 ]]; do
+    key="$1"
+    case "$key" in
+      # :flag.case
+      --deep | -d)
+
+        # :flag.case_no_arg
+        args['--deep']=1
+        shift
+        ;;
+
+      -?*)
+        printf "invalid option: %s\n" "$key" >&2
+        exit 1
+        ;;
+
+      *)
+        # :command.parse_requirements_case
+        # :command.parse_requirements_case_simple
+        printf "invalid argument: %s\n" "$key" >&2
+        exit 1
+
+        ;;
+
+    esac
+  done
+
+}
+
 # :command.initialize
 initialize() {
   version="0.1.0"
@@ -1031,6 +1166,7 @@ run() {
     "excitations") dvmc_excitations_command ;;
     "process-output") dvmc_process_output_command ;;
     "qmatrix") dvmc_qmatrix_command ;;
+    "clean") dvmc_clean_command ;;
   esac
 }
 
